// src/App.tsx
import { useState } from 'react';
import { StartList } from './components/StartList';
import { Timekeeping } from './components/Timekeeping';
import { Evaluation } from './components/Evaluation';
import { Snackbar } from './components/Snackbar';

type DisplayTarget = 'startlist' | 'timekeeping' | 'evaluation';

export function App() {
  const [displayTarget, setDisplayTarget] = useState<DisplayTarget>('startlist');

  return (
    <>
      <h1>Zeitmessung</h1>
      <nav>
        <button onClick={() => setDisplayTarget('startlist')}>Startliste</button>
        <button onClick={() => setDisplayTarget('timekeeping')}>
          Zeitmessung
        </button>
        <button onClick={() => setDisplayTarget('evaluation')}>Auswertung</button>
      </nav>

      {displayTarget === 'startlist' && <StartList />}
      {displayTarget === 'timekeeping' && <Timekeeping />}
      {displayTarget === 'evaluation' && <Evaluation />}

      <Snackbar />
    </>
  );
}

// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  standalone: false,
})
export class AppComponent {
  displayTarget = 'startlist';
}

<h1>Zeitmessung</h1>
<nav>
  <button (click)="displayTarget = 'startlist'">Startliste</button>
  <button (click)="displayTarget = 'timekeeping'">Zeitmessung</button>
  <button (click)="displayTarget = 'evaluation'">Auswertung</button>
</nav>

@if (displayTarget === 'startlist') {
  <app-start-list></app-start-list>
}
@if (displayTarget === 'timekeeping') {
  <app-timekeeping></app-timekeeping>
}
@if (displayTarget === 'evaluation') {
  <app-evaluation></app-evaluation>
}

<app-snackbar></app-snackbar>
